# Generated by Django 4.2.1 on 2023-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
