# Generated by Django 4.2.1 on 2023-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="file_name",
            field=models.CharField(
                db_index=True, default=1, max_length=160, unique=True
            ),
        ),
    ]
